# Generated by Django 4.2.6 on 2023-10-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.position'),
        ),
    ]
