# Generated by Django 4.2.6 on 2023-10-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sdutent',
            new_name='Student',
        ),
    ]
